[[scripts]]
name = "tests"
description = "Extensive automated sentence testing for the yo do"
binary = "yo-tests"
category = "🗣️ Voice"
log_level = "INFO"

[[scripts.parameters]]
name = "input"
description = "Text to test as a single sentence test"
optional = true

[[scripts.parameters]]
name = "stats"
type = "bool"
description = "Flag to display voice commands information like generated regex patterns, generated phrases and ratio"
optional = true

[[scripts.parameters]]
name = "fuzzy"
type = "int"
description = "Minimum percentage for considering fuzzy matching successful. (1-100)"
default = 30
