[[scripts]]
name = "weather"
description = "Tells current weather conditions"
category = "Miscellaneous"
code = '''
WEATHER=$(curl -sL "wttr.in/?format=%t+%C+%w" | sed 's/  */ /g' | xargs)
if [ -n "$WEATHER" ] && [ "$WEATHER" != "Unknown location" ]; then
  echo "Current weather: $WEATHER"
  yo say "Currently, the weather is $WEATHER"
else
  echoo "Error fetching weather"
  yo say "Error fetching weather"
fi
'''

[scripts.voice]
enabled = true
priority = 2
sentences = [
    "(what|whats) [is] the weather [like] [today|right] [now]",
    "weather report",
    "(how|hows) [is] the weather",
    "(what|whats) [is] the temperature"
]
